# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcid', models.CharField(max_length=5)),
                ('cid', models.CharField(max_length=20)),
                ('lastfinishedtime', models.DateTimeField(null=True)),
                ('step_1_status', models.CharField(max_length=10)),
                ('step_1_time', models.DateTimeField(null=True)),
                ('step_2_status', models.CharField(max_length=10)),
                ('step_2_time', models.DateTimeField(null=True)),
                ('step_3_status', models.CharField(max_length=10)),
                ('step_3_time', models.DateTimeField(null=True)),
                ('step_4_status', models.CharField(max_length=10)),
                ('step_4_time', models.DateTimeField(null=True)),
                ('step_2_clutser_status', models.IntegerField(default=0)),
                ('step_2_cluster_alpha', models.FloatField(default=0.85)),
                ('step_2_feature_limit', models.IntegerField(default=10)),
            ],
        ),
    ]
